inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.3

Bundler/OrderedGems:
  Enabled: false

Lint/EmptyWhen:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/SafeNavigation:
  Enabled: false

Style/StringLiterals:
  # EnforcedStyle: double_quotes
  Enabled: false

Style/TrailingCommaInArguments:
  # If `comma`, the cop requires a comma after the last argument, but only for
  # parenthesized method calls where each argument is on its own line.
  # If `consistent_comma`, the cop requires a comma after the last argument,
  # for all parenthesized method calls with arguments.
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInLiteral:
  # If `comma`, the cop requires a comma after the last item in an array or
  # hash, but only when each item is on its own line.
  # If `consistent_comma`, the cop requires a comma after the last item of all
  # non-empty array and hash literals.
  EnforcedStyleForMultiline: comma

Style/GuardClause:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 23

Metrics/PerceivedComplexity:
  Max: 23

Style/DoubleNegation:
  Enabled: false

Style/NegatedIf:
  Enabled: false

Style/PerlBackrefs:
  Enabled: false

Style/Next:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/SignalException:
  EnforcedStyle: semantic

Style/ClassVars:
  Exclude:
    - app/models/country.rb

Style/IfInsideElse:
  Enabled: false

Style/AsciiComments:
  Enabled: false
